### ISSUE TITLE
Error when using

### ISSUE THREAD

**Issue by egh** [conao3/dired-git.el#2]
After `(add-hook 'dired-mode-hook #'dired-git-mode)` I get this error when entering a dired buffer:

```
Warning (emacs): Fail dired-git-refresh
  buffer: #<buffer .emacs.d>
  reason: (wrong-number-of-arguments (1 . 1) 3)
```

unfortunately `condition-case` is preventing me from seeing the backtrace for this error, so I'm not sure where it's coming from

I'm using beta snap emacs (https://snapcraft.io/emacs) on ubuntu 20.04

```
GNU Emacs 27.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10) of 2020-05-24
```

**Comment by conao3** [comment]
Thanks for using my package :tada:
This breakage comes from my changes on promise upstream.
https://github.com/conao3/dired-git.el/commit/2b258fa4f0811443e4dbafbc94ea6756062420f6 may helps us.

FYI: I'm planing this package completely rewrite using magit-section!
Please wait for this awesome news!

**Comment by egh** [comment]
Great, thank you!
